//! Every word the skill-runner proxy can say, and the status table it says
//! it under (#273, ADR-0018).
//!
//! The proxy itself lives in the `wasm32` shim, because the egress has to
//! happen above the Durable Object: `microtask.apply` calls back into
//! `/api/steps` with the runner's own token, so routing the run through the
//! DO would make it await a subrequest that needs the same object to
//! answer. But `server/worker` has no test harness, so everything
//! *decidable* about the proxy — which upstream statuses may be forwarded
//! verbatim, what a failure reads like, how the runner's URL is built —
//! lives here, natively tested, and the shim contains no string literal and
//! no status arithmetic of its own.
//!
//! Every failure this module names is **one NDJSON envelope line**, the
//! same shape the runner's own terminal line has, so the client parses one
//! thing and never branches on prose. The two exceptions are the 401 and
//! the 403, whose empty bodies already carry a client contract (ADR-0004's
//! re-prompt semantics), and which the pure handler answers before the
//! proxy is ever reached.

/// A proxy-generated failure: the status to answer with, and the single
/// NDJSON line to answer it with.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProxyFailure {
    pub status: u16,
    /// One NDJSON line — a JSON object, newline-terminated.
    pub body: String,
}

fn failure(status: u16, error: &str) -> ProxyFailure {
    // Hand-built rather than via serde so the key order is the runner's own
    // (`ok`, `skill`, `error`) and the shape is legible right here. `error`
    // is escaped properly because it goes through `serde_json`.
    let error = serde_json::to_string(error).expect("a str serializes");
    ProxyFailure {
        status,
        body: format!("{{\"ok\":false,\"skill\":null,\"error\":{error}}}\n"),
    }
}

/// `RUNNER_BASE_URL`/`RUNNER_BEARER_TOKEN` unset. **503, never 401** — a
/// 401 would be a lie that makes the client re-prompt a device token that
/// is perfectly fine. Fails closed, mirroring `ADMIN_SECRET`'s posture in
/// `handlers::auth::admin_ok`.
pub fn unconfigured() -> ProxyFailure {
    failure(503, "The cloud runner is not configured on this server.")
}

/// The subrequest itself errored — DNS, TLS, connection, the Fly app down.
pub fn unreachable() -> ProxyFailure {
    failure(502, "Cloud runner unreachable.")
}

/// The runner answered 401: **this server's** bearer is wrong (rotated on
/// one side only), not the caller's. Forwarding the 401 would re-prompt the
/// user for a credential that is fine, so it becomes a 502.
pub fn credential_rejected() -> ProxyFailure {
    failure(502, "The cloud runner rejected this server's credential.")
}

/// Any other upstream status — a Fly 502 with an HTML body, a 500, a 404
/// from a misconfigured base URL.
pub fn upstream_status(status: u16) -> ProxyFailure {
    failure(502, &format!("The cloud runner answered {status}."))
}

/// The only upstream statuses whose body is the runner's own valid NDJSON
/// and may therefore be forwarded verbatim: 200 (the stream), 400 (a
/// validation decline) and 413 (a too-large body). **401 is deliberately
/// not here** — see [`credential_rejected`] — and neither is anything
/// generated by the platform in front of the runner, whose body is HTML and
/// would break the always-NDJSON promise.
pub fn forwardable(runner_status: u16) -> bool {
    matches!(runner_status, 200 | 400 | 413)
}

/// The runner's `POST /run` URL from its configured base, tolerating a
/// trailing slash on the secret.
pub fn run_url(base: &str) -> String {
    format!("{}/run", base.trim_end_matches('/'))
}
